"""
Natural Language Query Executor

This module executes the actual API calls generated by the parameter mapper
and returns real data from the services.
"""

import json
import pandas as pd
from typing import Dict, Any, List

class QueryExecutor:
    """Executes natural language queries against real NBA services"""
    
    def __init__(self, db_engine):
        """
        Initialize the executor with database engine
        
        Args:
            db_engine: SQLAlchemy database engine
        """
        self.engine = db_engine
        
        # Import services dynamically to avoid circular imports
        from ..game_service import GameService
        from ..player_service import PlayerService
        
        self.game_service = GameService(db_engine)
        self.player_service = PlayerService(db_engine)
    
    def execute_query(self, api_info: Dict[str, Any]) -> Dict[str, Any]:
        """
        Execute the API calls and return real results
        
        Args:
            api_info: API call information from parameter mapper
            
        Returns:
            Dict containing execution results and data
        """
        results = {
            "query_info": {
                "endpoint": api_info["endpoint"],
                "description": api_info["description"]
            },
            "api_calls": [],
            "data": None,
            "summary": None,
            "execution_time": None
        }
        
        import time
        start_time = time.time()
        
        try:
            # Execute each API call
            for i, api_call in enumerate(api_info["api_calls"]):
                call_result = self._execute_single_call(api_call)
                results["api_calls"].append(call_result)
                
                # Use the data from the primary call
                if i == 0 and call_result["success"]:
                    results["data"] = call_result["data"]
                    results["summary"] = self._generate_summary(call_result["data"], api_info["endpoint"])
            
            results["execution_time"] = f"{time.time() - start_time:.2f} seconds"
            
        except Exception as e:
            results["error"] = str(e)
            results["execution_time"] = f"{time.time() - start_time:.2f} seconds"
        
        return results
    
    def _execute_single_call(self, api_call: Dict[str, Any]) -> Dict[str, Any]:
        """Execute a single API call"""
        call_result = {
            "service": api_call["service"],
            "method": api_call["method"],
            "parameters": api_call["parameters"],
            "purpose": api_call["purpose"],
            "success": False,
            "data": None,
            "error": None
        }
        
        try:
            # Route to appropriate service based on service name
            if "game_service" in api_call["service"]:
                call_result["data"] = self._call_game_service(api_call)
            elif "player_service" in api_call["service"]:
                call_result["data"] = self._call_player_service(api_call)
            else:
                raise ValueError(f"Unknown service: {api_call['service']}")
            
            call_result["success"] = True
            
        except Exception as e:
            call_result["error"] = str(e)
            call_result["success"] = False
        
        return call_result
    
    def _call_game_service(self, api_call: Dict[str, Any]) -> Any:
        """Call GameService methods"""
        method = api_call["method"]
        params = api_call["parameters"]
        
        if method == "get_filtered_logs":
            # Convert parameters to the format expected by GameService
            filter_params = self._convert_to_game_service_params(params)
            player_name = params.get("player_name")
            
            if not player_name:
                raise ValueError("player_name is required for get_filtered_logs")
            
            return self.game_service.get_filtered_logs(player_name, filter_params)
        else:
            raise ValueError(f"Unknown GameService method: {method}")
    
    def _call_player_service(self, api_call: Dict[str, Any]) -> Any:
        """Call PlayerService methods"""
        method = api_call["method"]
        params = api_call["parameters"]
        
        if method == "get_player_profile":
            player_name = params.get("player_name")
            category = params.get("category", "Playtypes")
            
            if not player_name:
                raise ValueError("player_name is required for get_player_profile")
            
            return self.player_service.get_player_profile(player_name, category)
        else:
            raise ValueError(f"Unknown PlayerService method: {method}")
    
    def _convert_to_game_service_params(self, params: Dict[str, Any]) -> Dict[str, Any]:
        """Convert mapped parameters to GameService format"""
        filter_params = {
            'minutes_filter': (0, 48),  # Default
            'players_on': [],
            'players_off': [],
            'date_filter': None,
            'teams_against': [],
            'rank_filter': [],
            'location_filter': 'Both',
            'game_filter': None,
            'season_filter': '2024-25',
            'playstyle_range': [0, 200],
            'self_filters': {}
        }
        
        # Map parameters
        if params.get("game_filter"):
            filter_params["game_filter"] = params["game_filter"]
        
        if params.get("location_filter"):
            filter_params["location_filter"] = params["location_filter"]
        
        if params.get("season_filter"):
            filter_params["season_filter"] = params["season_filter"]
        
        if params.get("teams_against"):
            filter_params["teams_against"] = params["teams_against"]
            
        if params.get("rank_filter"):
            filter_params["rank_filter"] = params["rank_filter"]
        
        if params.get("players_on"):
            filter_params["players_on"] = params["players_on"]
            
        if params.get("players_off"):
            filter_params["players_off"] = params["players_off"]
        
        return filter_params
    
    def _generate_summary(self, data: Any, endpoint: str) -> Dict[str, Any]:
        """Generate a summary of the results"""
        summary = {"endpoint": endpoint}
        
        try:
            if endpoint == "game_logs" and isinstance(data, dict):
                # Parse the JSON data from GameService
                if "game_logs" in data:
                    game_logs = json.loads(data["game_logs"])
                    summary["total_games"] = len(game_logs)
                    
                    if game_logs:
                        # Calculate some quick stats
                        points = [game.get("PTS", 0) for game in game_logs]
                        rebounds = [game.get("REB", 0) for game in game_logs]
                        assists = [game.get("AST", 0) for game in game_logs]
                        
                        summary["stats"] = {
                            "avg_points": round(sum(points) / len(points), 1) if points else 0,
                            "avg_rebounds": round(sum(rebounds) / len(rebounds), 1) if rebounds else 0,
                            "avg_assists": round(sum(assists) / len(assists), 1) if assists else 0,
                            "games_analyzed": len(game_logs)
                        }
                
                if "averages" in data:
                    averages = json.loads(data["averages"])
                    if averages:
                        summary["period_averages"] = averages[0]
                
                if "season_averages" in data:
                    season_averages = json.loads(data["season_averages"])
                    if season_averages:
                        summary["season_averages"] = season_averages[0]
            
            elif endpoint == "player_profile":
                summary["profile_data"] = "Player profile information retrieved"
                
        except Exception as e:
            summary["error"] = f"Error generating summary: {str(e)}"
        
        return summary 